Avishkar/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
]

home/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name="home"

urlpatterns = [
    path('',views.index,name='index'),
    path('contactus',views.contactus,name='contactus'),
    path('aboutus',views.aboutus,name='aboutus'),
    path('products',views.products,name='products'),
    path('addproduct',views.addproduct,name='addproduct'),
   
]

home/models.py
from django.db import models
from django.db.models import query
from django.db.models.fields.files import ImageField

# Create your models here.
class ContactUs(models.Model):
    name=models.CharField(max_length=30)
    phone=models.IntegerField()
    email=models.EmailField()
    query=models.TextField()

class AddProduct(models.Model):
    name=models.CharField(max_length=30)
    price=models.IntegerField(blank=True,null=True)
    description=models.TextField()
    image=models.ImageField(upload_to="home/index", default="",blank=True,null=True)

home/views.py
from django.shortcuts import render,redirect
from .form import *
from .models import *

# Create your views here.
def index(req):
    return render(req,'index.html')

def contactus(req):
    if req.method=="POST":
       obj=ContactUsForm(req.POST)
       obj.save() 
       return redirect('home:contactus')
    else :
        obj=ContactUsForm()
        return render(req,'contactus.html',{'form':obj})

def aboutus(req):
    return render(req,'aboutus.html')

def products(req):
    return render(req,'products.html')

def addproduct(req):
    if req.method=="POST":
        obj=AddProductForm()
        obj.save()
        return redirect('home:addproduct')
    else :
        obj=AddProductForm()
        return render(req,'addproduct.html',{'form':obj})

home/templates/aboutus.html
{% extends 'base.html' %} {% block title %} About Us {% endblock %} {% block content %} {% load static %}

<div class="container">
<div class="about-section">
  <p class="text-center">
  <h1>About Us Page</h1>
  <p>Some text about who we are and what we do.</p>
  <p>Resize the browser window to see that this page is responsive by the way.</p>
  </p>
</div>

<h2 style="text-align:center">Our Team</h2>

<div class="card-group">
  <div class="card">
    <img src="..." class="card-img-top" alt="...">
    <!-- <div class="card-body">
      <h5 class="card-title">Kavita Jadhav</h5>
      <p class="card-text">Designer & Founder</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div> -->
    <div class="container">
      <h2>Kavita Jadhav</h2>
      <p class="title">Designer & Founder</p>
      <p>Some text that describes me lorem ipsum ipsum lorem.</p>
      <p>kmjadhav9970@gmail.com</p>
      <p><button class="button">Contact</button></p>
    </div>
  </div>
  <div class="card">
    <img src="..." class="card-img-top" alt="...">
    <!--<div class="card-body">
      <h5 class="card-title">Archana Mane</h5>
      <p class="card-text">Photographer & Founder</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>-->
    <div class="container">
      <h2>Archana Mane</h2>
      <p class="title">Photographer & Founder</p>
      <p>Some text that describes me lorem ipsum ipsum lorem.</p>
      <p>abc@gmail.com</p>
      <p><button class="button">Contact</button></p>
    </div>
  </div>
</div>
</div>

  {% endblock %}

home/templates/addproduct.html
{% extends 'base.html' %} {% block title %} Contact Us {% endblock %} {% block content %} {% load static %}

<div class="container">
 <form method="POST">
    {% csrf_token %}
    {%for field in form%}
    <div class="cust-form-row">
        {{field.errors}}
        <label for="{{ field.id_for_label }}">
            {{ field.label }}{% if field.field.required %}:{% endif %}
        </label><br> {{field}}
        <br>
    </div>
    {%endfor%}
    <div class="form-controls">
        <button type="submit" class="btn btn-success mt-1">Save</button>
    </div>
<!--</form>--> 

<div class="container">
    <div class="row">
            {% for k in obj %}
                <div class="col-sm-4">
                    <div class="card" style="width: 18rem;">
                      <img src="...." class="card-img-top" alt="...">
                      <div class="card-body">
                        <h5 class="card-title">{{ k.name }}</h5>
                        <p class="card-text">Text here</p>
                      </div>
                      <ul class="list-group list-group-flush">
                        <li class="list-group-item">{{ k.price }}</li>
                        <li class="list-group-item">{{ k.description }}</li>
                        <li class="list-group-item">{{ k.image }}</li>
                      </ul>
                      <div class="card-body">
                        <a href="#" class="card-link">Card link</a>
                        <a href="#" class="card-link">Another link</a>
                      </div>
                    </div>
                </div>
            {% endfor %}
  </form>
</div>
{% endblock %}

home/templates/base.html
<!doctype html>
<html lang="en">
  {% load static %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top " style="">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home:index' %}">
            <img src="{% static 'logo.jpeg' %}" style="height: 50px; width: 140px;">
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home:products' %}">Our Products</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home:aboutus' %}">About Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home:contactus' %}">Contact Us</a>
              </li>
            </ul>
           </div>     
        </div>
      </nav>

    {% block content %}  {% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

home/templates/contactus.html
{% extends 'base.html' %} {% block title %} Contact Us {% endblock %} {% block content %} {% load static %}

<div class="container">
    <div class="container">
        
        <div class="row">
          <div class="col">
            Our Location
            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d3814.249950988625!2d73.7958976653613!3d18.664893098467395!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sin!4v1628006279949!5m2!1sen!2sin" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>

          </div>
          <div class="col">
            Tell us what you want 
        <p>
        <form method="POST">
            {% csrf_token %}
            {%for field in form%}
            <div class="cust-form-row">
                {{field.errors}}
                <label for="{{ field.id_for_label }}">
                    {{ field.label }}{% if field.field.required %}:{% endif %}
                </label><br> {{field}}
                <br>
            </div>
            {%endfor%}
            <div class="form-controls">
                <button type="submit" class="btn btn-success mt-1">Save</button>
            </div>
        </form>
        </p>
        </div>
        </div>
    </div>

</div>

{% endblock %}

home/templates/index.html
{% extends 'base.html' %} {% block title %} Avishkar Creations {% endblock %} {% block content %} {% load static %}
<div class="container">
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel" >
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static '1.png'%}" class="d-block w-100" alt="..." style="width: 100%; height: 35vw;">
        <div class="carousel-caption d-none d-md-block">
          <h5>First slide label</h5>
          <p>Some representative placeholder content for the first slide.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static '2.png'%}" class="d-block w-100" alt="..." style="width: 100%; height: 35vw;">
        <div class="carousel-caption d-none d-md-block">
          <h5>Second slide label</h5>
          <p>Some representative placeholder content for the second slide.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static '3.png'%}" class="d-block w-100" alt="..."style="width: 100%; height: 35vw;">
        <div class="carousel-caption d-none d-md-block">
          <h5>Third slide label</h5>
          <p>Some representative placeholder content for the third slide.</p>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>


</div>
{% endblock %}

home/templates/products.html
{% extends 'base.html' %} {% block title %} Products {% endblock %} {% block content %} {% load static %}

<div class="container">
<br>
        <div class="row">
        <div class="col-4">
          <div class="card"><img src="{%static '3.png'%}" class="card-img-top" alt="..." height="300px">
            <div class="card-body">
                <h5 class="card-title">Jwellery</h5>
                <p class="card-text">Made with fine material and with good quality components</p>
            </div>
            <div class="card-footer">
                Price: 100/-
            </div></div>
        </div>
        <div class="col-4">
          <div class="card"><img src="{%static '3.png'%}" class="card-img-top" alt="..." height="300px">
            <div class="card-body">
                <h5 class="card-title">Jwellery</h5>
                <p class="card-text">Made with fine material and with good quality components.</p>
            </div>
            <div class="card-footer">
                Price: 100/-
            </div></div>
        </div>
        <div class="col-4">
          <div class="card"><img src="{%static '3.png'%}" class="card-img-top" alt="..." height="300px">
            <div class="card-body">
                <h5 class="card-title">Jwellery</h5>
                <p class="card-text">Made with fine material and with good quality components</p>
            </div>
            <div class="card-footer">
                Price: 100/-
            </div></div>
        </div>
      </div>
<br>
      
      <div class="row">
        <div class="col-4">
          <div class="card"><img src="{%static '1.png'%}" class="card-img-top" alt="..." height="300px">
            <div class="card-body">
                <h5 class="card-title">Jwellery</h5>
                <p class="card-text">Made with fine material and with good quality components</p>
            </div>
            <div class="card-footer">
                Price: 100/-
            </div></div>
        </div>
        <div class="col-4">
          <div class="card"><img src="{%static '1.png'%}" class="card-img-top" alt="..." height="300px">
            <div class="card-body">
                <h5 class="card-title">Jwellery</h5>
                <p class="card-text">Made with fine material and with good quality components.</p>
            </div>
            <div class="card-footer">
                Price: 100/-
            </div></div>
        </div>
        <div class="col-4">
          <div class="card"><img src="{%static '1.png'%}" class="card-img-top" alt="..." height="300px">
            <div class="card-body">
                <h5 class="card-title">Jwellery</h5>
                <p class="card-text">Made with fine material and with good quality components</p>
            </div>
            <div class="card-footer">
                Price: 100/-
            </div></div>
        </div>
      </div>
<br>
      
      <div class="row">
        <div class="col-4">
          <div class="card"><img src="{%static '2.png'%}" class="card-img-top" alt="..." height="300px">
            <div class="card-body">
                <h5 class="card-title">Jwellery</h5>
                <p class="card-text">Made with fine material and with good quality components</p>
            </div>
            <div class="card-footer">
                Price: 100/-
            </div></div>
        </div>
        <div class="col-4">
          <div class="card"><img src="{%static '2.png'%}" class="card-img-top" alt="..." height="300px">
            <div class="card-body">
                <h5 class="card-title">Jwellery</h5>
                <p class="card-text">Made with fine material and with good quality components.</p>
            </div>
            <div class="card-footer">
                Price: 100/-
            </div></div>
        </div>
        <div class="col-4">
          <div class="card"><img src="{%static '2.png'%}" class="card-img-top" alt="..." height="300px">
            <div class="card-body">
                <h5 class="card-title">Jwellery</h5>
                <p class="card-text">Made with fine material and with good quality components</p>
            </div>
            <div class="card-footer">
                Price: 100/-
            </div></div>
        </div>
      </div>
</div>


  {% endblock %}